cache = "~/.config/nixmodule"

[[kernels]]
version = "5.17.2"
url_base = "localhost:8000"
headers = "linux-5.17.2-guest.tar.gz" 
kernel = "linux-5.17.2/arch/x86/boot/bzImage"
disk = "linux-5.17.2-build/image/stretch.img"
sshkey = "linux-5.17.2-build/image/stretch.id_rsa"
keyfile = "stretch.id_rsa"
runner = "qemu-system-x86_64"
