#######################################################
# Cache Config
#######################################################
cache = "~/.cache/nixmodule"

#######################################################
# Module Config
#######################################################

[module]
name = "drawbridge"

#######################################################
# 5.17.2 Test
#######################################################
[[kernels]]
version = "5.17.2"
url_base = "https://files.sboc.dev"
headers = "linux-headers/linux-5.17.2-headers.tar.gz" 
kernel = "linux-kernels/bzImage-5.17.2"
runner = "qemu-system-x86_64"

[kernels.disk]
name = "stretch"
url_base = "https://files.sboc.dev"
path = "images/stretch/stretch.img"
sshkey = "images/stretch/stretch.id_rsa"

#######################################################
# 5.8.9 Test
#######################################################
[[kernels]]
version = "5.8.9"
url_base = "https://files.sboc.dev"
headers = "linux-headers/linux-5.8.9-headers.tar.gz" 
kernel = "linux-kernels/bzImage-5.8.9"
runner = "qemu-system-x86_64"

[kernels.disk]
name = "stretch"
url_base = "https://files.sboc.dev"
path = "images/stretch/stretch.img"
sshkey = "images/stretch/stretch.id_rsa"