#######################################################
# Cache Config
#######################################################
cache = "~/.cache/nixmodule"

#######################################################
# Module Config
#######################################################

[module]
name = "drawbridge"
insmod_args = "ports=8000"

[module.test_script]
local = "./tests/test.sh"
remote = "/tmp/test.sh"

[[module.test_files]]
local = "../tools/target/x86_64-unknown-linux-musl/release/db"
remote = "/usr/bin/db"

[[module.test_files]]
local = "/tmp/test_key"
remote = "/tmp/test_key"

#######################################################
# 5.17.2 Test
#######################################################
[[kernels]]
version = "5.17.2"
url_base = "https://files.sboc.dev"
headers = "linux-headers/linux-5.17.2-headers.tar.gz" 
kernel = "linux-kernels/bzImage-5.17.2"
runner = "qemu-system-x86_64"

[kernels.disk]
name = "stretch"
url_base = "https://files.sboc.dev"
path = "images/stretch/stretch.img"
sshkey = "images/stretch/stretch.id_rsa"

#######################################################
# 5.8.9 Test
#######################################################
[[kernels]]
version = "5.8.9"
url_base = "https://files.sboc.dev"
headers = "linux-headers/linux-5.8.9-headers.tar.gz" 
kernel = "linux-kernels/bzImage-5.8.9"
runner = "qemu-system-x86_64"

[kernels.disk]
name = "stretch"
url_base = "https://files.sboc.dev"
path = "images/stretch/stretch.img"
sshkey = "images/stretch/stretch.id_rsa"